// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airbyte-test/pkg/models/shared"
	"net/http"
)

type GetAttemptNormalizationStatusesForJobResponse struct {
	// Successful operation
	AttemptNormalizationStatusReadList *shared.AttemptNormalizationStatusReadList
	ContentType                        string
	StatusCode                         int
	RawResponse                        *http.Response
}
