// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airbyte-test/pkg/models/shared"
	"net/http"
)

type GetHealthCheckResponse struct {
	ContentType string
	// Successful operation
	HealthCheckRead *shared.HealthCheckRead
	StatusCode      int
	RawResponse     *http.Response
}
