// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airbyte-test/pkg/models/shared"
	"net/http"
)

type ListSourceDefinitionsForWorkspaceResponse struct {
	ContentType string
	// Successful operation
	SourceDefinitionReadList *shared.SourceDefinitionReadList
	StatusCode               int
	RawResponse              *http.Response
}
