// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ActorCatalogWithUpdatedAt - A source actor catalog with the timestamp it was mostly recently updated
type ActorCatalogWithUpdatedAt struct {
	Catalog   map[string]interface{} `json:"catalog,omitempty"`
	UpdatedAt *int64                 `json:"updatedAt,omitempty"`
}
