// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AttemptFailureType - Categorizes well known errors into types for programmatic handling. If not set, the type of error is not well known.
type AttemptFailureType string

const (
	AttemptFailureTypeConfigError        AttemptFailureType = "config_error"
	AttemptFailureTypeSystemError        AttemptFailureType = "system_error"
	AttemptFailureTypeManualCancellation AttemptFailureType = "manual_cancellation"
	AttemptFailureTypeRefreshSchema      AttemptFailureType = "refresh_schema"
)

func (e AttemptFailureType) ToPointer() *AttemptFailureType {
	return &e
}

func (e *AttemptFailureType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "config_error":
		fallthrough
	case "system_error":
		fallthrough
	case "manual_cancellation":
		fallthrough
	case "refresh_schema":
		*e = AttemptFailureType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AttemptFailureType: %v", v)
	}
}
