// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AttemptFailureOrigin - Indicates where the error originated. If not set, the origin of error is not well known.
type AttemptFailureOrigin string

const (
	AttemptFailureOriginSource          AttemptFailureOrigin = "source"
	AttemptFailureOriginDestination     AttemptFailureOrigin = "destination"
	AttemptFailureOriginReplication     AttemptFailureOrigin = "replication"
	AttemptFailureOriginPersistence     AttemptFailureOrigin = "persistence"
	AttemptFailureOriginNormalization   AttemptFailureOrigin = "normalization"
	AttemptFailureOriginDbt             AttemptFailureOrigin = "dbt"
	AttemptFailureOriginAirbytePlatform AttemptFailureOrigin = "airbyte_platform"
	AttemptFailureOriginUnknown         AttemptFailureOrigin = "unknown"
)

func (e AttemptFailureOrigin) ToPointer() *AttemptFailureOrigin {
	return &e
}

func (e *AttemptFailureOrigin) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "source":
		fallthrough
	case "destination":
		fallthrough
	case "replication":
		fallthrough
	case "persistence":
		fallthrough
	case "normalization":
		fallthrough
	case "dbt":
		fallthrough
	case "airbyte_platform":
		fallthrough
	case "unknown":
		*e = AttemptFailureOrigin(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AttemptFailureOrigin: %v", v)
	}
}
