// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AttemptFailureTypeEnum - Categorizes well known errors into types for programmatic handling. If not set, the type of error is not well known.
type AttemptFailureTypeEnum string

const (
	AttemptFailureTypeEnumConfigError        AttemptFailureTypeEnum = "config_error"
	AttemptFailureTypeEnumSystemError        AttemptFailureTypeEnum = "system_error"
	AttemptFailureTypeEnumManualCancellation AttemptFailureTypeEnum = "manual_cancellation"
	AttemptFailureTypeEnumRefreshSchema      AttemptFailureTypeEnum = "refresh_schema"
)

func (e AttemptFailureTypeEnum) ToPointer() *AttemptFailureTypeEnum {
	return &e
}

func (e *AttemptFailureTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "config_error":
		fallthrough
	case "system_error":
		fallthrough
	case "manual_cancellation":
		fallthrough
	case "refresh_schema":
		*e = AttemptFailureTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AttemptFailureTypeEnum: %v", v)
	}
}
