// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type CheckConnectionReadStatusEnum string

const (
	CheckConnectionReadStatusEnumSucceeded CheckConnectionReadStatusEnum = "succeeded"
	CheckConnectionReadStatusEnumFailed    CheckConnectionReadStatusEnum = "failed"
)

func (e CheckConnectionReadStatusEnum) ToPointer() *CheckConnectionReadStatusEnum {
	return &e
}

func (e *CheckConnectionReadStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "failed":
		*e = CheckConnectionReadStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CheckConnectionReadStatusEnum: %v", v)
	}
}

// CheckConnectionRead - Successful operation
type CheckConnectionRead struct {
	JobInfo SynchronousJobRead            `json:"jobInfo"`
	Message *string                       `json:"message,omitempty"`
	Status  CheckConnectionReadStatusEnum `json:"status"`
}
