// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ConnectionScheduleTypeEnum - determine how the schedule data should be interpreted
type ConnectionScheduleTypeEnum string

const (
	ConnectionScheduleTypeEnumManual ConnectionScheduleTypeEnum = "manual"
	ConnectionScheduleTypeEnumBasic  ConnectionScheduleTypeEnum = "basic"
	ConnectionScheduleTypeEnumCron   ConnectionScheduleTypeEnum = "cron"
)

func (e ConnectionScheduleTypeEnum) ToPointer() *ConnectionScheduleTypeEnum {
	return &e
}

func (e *ConnectionScheduleTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manual":
		fallthrough
	case "basic":
		fallthrough
	case "cron":
		*e = ConnectionScheduleTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionScheduleTypeEnum: %v", v)
	}
}
