// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ConnectionScheduleDataBasicScheduleTimeUnitEnum string

const (
	ConnectionScheduleDataBasicScheduleTimeUnitEnumMinutes ConnectionScheduleDataBasicScheduleTimeUnitEnum = "minutes"
	ConnectionScheduleDataBasicScheduleTimeUnitEnumHours   ConnectionScheduleDataBasicScheduleTimeUnitEnum = "hours"
	ConnectionScheduleDataBasicScheduleTimeUnitEnumDays    ConnectionScheduleDataBasicScheduleTimeUnitEnum = "days"
	ConnectionScheduleDataBasicScheduleTimeUnitEnumWeeks   ConnectionScheduleDataBasicScheduleTimeUnitEnum = "weeks"
	ConnectionScheduleDataBasicScheduleTimeUnitEnumMonths  ConnectionScheduleDataBasicScheduleTimeUnitEnum = "months"
)

func (e ConnectionScheduleDataBasicScheduleTimeUnitEnum) ToPointer() *ConnectionScheduleDataBasicScheduleTimeUnitEnum {
	return &e
}

func (e *ConnectionScheduleDataBasicScheduleTimeUnitEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "minutes":
		fallthrough
	case "hours":
		fallthrough
	case "days":
		fallthrough
	case "weeks":
		fallthrough
	case "months":
		*e = ConnectionScheduleDataBasicScheduleTimeUnitEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionScheduleDataBasicScheduleTimeUnitEnum: %v", v)
	}
}

type ConnectionScheduleDataBasicSchedule struct {
	TimeUnit ConnectionScheduleDataBasicScheduleTimeUnitEnum `json:"timeUnit"`
	Units    int64                                           `json:"units"`
}

type ConnectionScheduleDataCron struct {
	CronExpression string `json:"cronExpression"`
	CronTimeZone   string `json:"cronTimeZone"`
}

// ConnectionScheduleData - schedule for when the the connection should run, per the schedule type
type ConnectionScheduleData struct {
	BasicSchedule *ConnectionScheduleDataBasicSchedule `json:"basicSchedule,omitempty"`
	Cron          *ConnectionScheduleDataCron          `json:"cron,omitempty"`
}
