// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type DestinationAuthSpecificationAuthTypeEnum string

const (
	DestinationAuthSpecificationAuthTypeEnumOauth20 DestinationAuthSpecificationAuthTypeEnum = "oauth2.0"
)

func (e DestinationAuthSpecificationAuthTypeEnum) ToPointer() *DestinationAuthSpecificationAuthTypeEnum {
	return &e
}

func (e *DestinationAuthSpecificationAuthTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oauth2.0":
		*e = DestinationAuthSpecificationAuthTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationAuthSpecificationAuthTypeEnum: %v", v)
	}
}

type DestinationAuthSpecification struct {
	AuthType *DestinationAuthSpecificationAuthTypeEnum `json:"auth_type,omitempty"`
	// An object containing any metadata needed to describe this connector's Oauth flow
	Oauth2Specification *OAuth2Specification `json:"oauth2Specification,omitempty"`
}
