// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type DestinationAuthSpecificationAuthType string

const (
	DestinationAuthSpecificationAuthTypeOauth20 DestinationAuthSpecificationAuthType = "oauth2.0"
)

func (e DestinationAuthSpecificationAuthType) ToPointer() *DestinationAuthSpecificationAuthType {
	return &e
}

func (e *DestinationAuthSpecificationAuthType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oauth2.0":
		*e = DestinationAuthSpecificationAuthType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationAuthSpecificationAuthType: %v", v)
	}
}

type DestinationAuthSpecification struct {
	AuthType *DestinationAuthSpecificationAuthType `json:"auth_type,omitempty"`
	// An object containing any metadata needed to describe this connector's Oauth flow
	Oauth2Specification *OAuth2Specification `json:"oauth2Specification,omitempty"`
}
