// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type FieldTransformTransformTypeEnum string

const (
	FieldTransformTransformTypeEnumAddField          FieldTransformTransformTypeEnum = "add_field"
	FieldTransformTransformTypeEnumRemoveField       FieldTransformTransformTypeEnum = "remove_field"
	FieldTransformTransformTypeEnumUpdateFieldSchema FieldTransformTransformTypeEnum = "update_field_schema"
)

func (e FieldTransformTransformTypeEnum) ToPointer() *FieldTransformTransformTypeEnum {
	return &e
}

func (e *FieldTransformTransformTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "add_field":
		fallthrough
	case "remove_field":
		fallthrough
	case "update_field_schema":
		*e = FieldTransformTransformTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FieldTransformTransformTypeEnum: %v", v)
	}
}

// FieldTransform - Describes the difference between two Streams.
type FieldTransform struct {
	AddField *FieldAdd `json:"addField,omitempty"`
	Breaking bool      `json:"breaking"`
	// A field name is a list of strings that form the path to the field.
	FieldName         []string                        `json:"fieldName"`
	RemoveField       *FieldRemove                    `json:"removeField,omitempty"`
	TransformType     FieldTransformTransformTypeEnum `json:"transformType"`
	UpdateFieldSchema *FieldSchemaUpdate              `json:"updateFieldSchema,omitempty"`
}
