// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FieldSchemaUpdate struct {
	// JSONSchema representation of the field
	NewSchema map[string]interface{} `json:"newSchema"`
	// JSONSchema representation of the field
	OldSchema map[string]interface{} `json:"oldSchema"`
}
