// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FieldRemove struct {
	// JSONSchema representation of the field
	Schema map[string]interface{} `json:"schema,omitempty"`
}
