// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GlobalState struct {
	SharedState  map[string]interface{} `json:"shared_state,omitempty"`
	StreamStates []StreamState          `json:"streamStates"`
}
