// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type JobConfigTypeEnum string

const (
	JobConfigTypeEnumCheckConnectionSource      JobConfigTypeEnum = "check_connection_source"
	JobConfigTypeEnumCheckConnectionDestination JobConfigTypeEnum = "check_connection_destination"
	JobConfigTypeEnumDiscoverSchema             JobConfigTypeEnum = "discover_schema"
	JobConfigTypeEnumGetSpec                    JobConfigTypeEnum = "get_spec"
	JobConfigTypeEnumSync                       JobConfigTypeEnum = "sync"
	JobConfigTypeEnumResetConnection            JobConfigTypeEnum = "reset_connection"
)

func (e JobConfigTypeEnum) ToPointer() *JobConfigTypeEnum {
	return &e
}

func (e *JobConfigTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "check_connection_source":
		fallthrough
	case "check_connection_destination":
		fallthrough
	case "discover_schema":
		fallthrough
	case "get_spec":
		fallthrough
	case "sync":
		fallthrough
	case "reset_connection":
		*e = JobConfigTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobConfigTypeEnum: %v", v)
	}
}
