// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobDebugRead struct {
	AirbyteVersion        string                    `json:"airbyteVersion"`
	ConfigID              string                    `json:"configId"`
	ConfigType            JobConfigTypeEnum         `json:"configType"`
	DestinationDefinition DestinationDefinitionRead `json:"destinationDefinition"`
	ID                    int64                     `json:"id"`
	SourceDefinition      SourceDefinitionRead      `json:"sourceDefinition"`
	Status                JobStatusEnum             `json:"status"`
}
