// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// JobTypeEnum - enum that describes the different types of jobs that the platform runs.
type JobTypeEnum string

const (
	JobTypeEnumGetSpec           JobTypeEnum = "get_spec"
	JobTypeEnumCheckConnection   JobTypeEnum = "check_connection"
	JobTypeEnumDiscoverSchema    JobTypeEnum = "discover_schema"
	JobTypeEnumSync              JobTypeEnum = "sync"
	JobTypeEnumResetConnection   JobTypeEnum = "reset_connection"
	JobTypeEnumConnectionUpdater JobTypeEnum = "connection_updater"
	JobTypeEnumReplicate         JobTypeEnum = "replicate"
)

func (e JobTypeEnum) ToPointer() *JobTypeEnum {
	return &e
}

func (e *JobTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "get_spec":
		fallthrough
	case "check_connection":
		fallthrough
	case "discover_schema":
		fallthrough
	case "sync":
		fallthrough
	case "reset_connection":
		fallthrough
	case "connection_updater":
		fallthrough
	case "replicate":
		*e = JobTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JobTypeEnum: %v", v)
	}
}
