// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// LogTypeEnum - type/source of logs produced
type LogTypeEnum string

const (
	LogTypeEnumServer    LogTypeEnum = "server"
	LogTypeEnumScheduler LogTypeEnum = "scheduler"
)

func (e LogTypeEnum) ToPointer() *LogTypeEnum {
	return &e
}

func (e *LogTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "server":
		fallthrough
	case "scheduler":
		*e = LogTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LogTypeEnum: %v", v)
	}
}
