// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// NamespaceDefinitionTypeEnum - Method used for computing final namespace in destination
type NamespaceDefinitionTypeEnum string

const (
	NamespaceDefinitionTypeEnumSource       NamespaceDefinitionTypeEnum = "source"
	NamespaceDefinitionTypeEnumDestination  NamespaceDefinitionTypeEnum = "destination"
	NamespaceDefinitionTypeEnumCustomformat NamespaceDefinitionTypeEnum = "customformat"
)

func (e NamespaceDefinitionTypeEnum) ToPointer() *NamespaceDefinitionTypeEnum {
	return &e
}

func (e *NamespaceDefinitionTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "source":
		fallthrough
	case "destination":
		fallthrough
	case "customformat":
		*e = NamespaceDefinitionTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NamespaceDefinitionTypeEnum: %v", v)
	}
}
