// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type NonBreakingChangesPreferenceEnum string

const (
	NonBreakingChangesPreferenceEnumIgnore  NonBreakingChangesPreferenceEnum = "ignore"
	NonBreakingChangesPreferenceEnumDisable NonBreakingChangesPreferenceEnum = "disable"
)

func (e NonBreakingChangesPreferenceEnum) ToPointer() *NonBreakingChangesPreferenceEnum {
	return &e
}

func (e *NonBreakingChangesPreferenceEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ignore":
		fallthrough
	case "disable":
		*e = NonBreakingChangesPreferenceEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NonBreakingChangesPreferenceEnum: %v", v)
	}
}
