// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type NotificationReadStatusEnum string

const (
	NotificationReadStatusEnumSucceeded NotificationReadStatusEnum = "succeeded"
	NotificationReadStatusEnumFailed    NotificationReadStatusEnum = "failed"
)

func (e NotificationReadStatusEnum) ToPointer() *NotificationReadStatusEnum {
	return &e
}

func (e *NotificationReadStatusEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "succeeded":
		fallthrough
	case "failed":
		*e = NotificationReadStatusEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NotificationReadStatusEnum: %v", v)
	}
}

// NotificationRead - Successful operation
type NotificationRead struct {
	Message *string                    `json:"message,omitempty"`
	Status  NotificationReadStatusEnum `json:"status"`
}
