// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type NotificationTypeEnum string

const (
	NotificationTypeEnumSlack      NotificationTypeEnum = "slack"
	NotificationTypeEnumCustomerio NotificationTypeEnum = "customerio"
)

func (e NotificationTypeEnum) ToPointer() *NotificationTypeEnum {
	return &e
}

func (e *NotificationTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "slack":
		fallthrough
	case "customerio":
		*e = NotificationTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for NotificationTypeEnum: %v", v)
	}
}
