// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OperatorWebhookDbtCloud struct {
	// The account id associated with the job
	AccountID int64 `json:"accountId"`
	// The job id associated with the job
	JobID int64 `json:"jobId"`
}

type OperatorWebhookWebhookTypeEnum string

const (
	OperatorWebhookWebhookTypeEnumDbtCloud OperatorWebhookWebhookTypeEnum = "dbtCloud"
)

func (e OperatorWebhookWebhookTypeEnum) ToPointer() *OperatorWebhookWebhookTypeEnum {
	return &e
}

func (e *OperatorWebhookWebhookTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dbtCloud":
		*e = OperatorWebhookWebhookTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OperatorWebhookWebhookTypeEnum: %v", v)
	}
}

type OperatorWebhook struct {
	DbtCloud *OperatorWebhookDbtCloud `json:"dbtCloud,omitempty"`
	// DEPRECATED. Populate dbtCloud instead.
	ExecutionBody *string `json:"executionBody,omitempty"`
	// DEPRECATED. Populate dbtCloud instead.
	ExecutionURL *string `json:"executionUrl,omitempty"`
	// The id of the webhook configs to use from the workspace.
	WebhookConfigID *string                         `json:"webhookConfigId,omitempty"`
	WebhookType     *OperatorWebhookWebhookTypeEnum `json:"webhookType,omitempty"`
}
