// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OperatorNormalizationOptionEnum string

const (
	OperatorNormalizationOptionEnumBasic OperatorNormalizationOptionEnum = "basic"
)

func (e OperatorNormalizationOptionEnum) ToPointer() *OperatorNormalizationOptionEnum {
	return &e
}

func (e *OperatorNormalizationOptionEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "basic":
		*e = OperatorNormalizationOptionEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OperatorNormalizationOptionEnum: %v", v)
	}
}

type OperatorNormalization struct {
	Option *OperatorNormalizationOptionEnum `json:"option,omitempty"`
}
