// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OperatorTypeEnum string

const (
	OperatorTypeEnumNormalization OperatorTypeEnum = "normalization"
	OperatorTypeEnumDbt           OperatorTypeEnum = "dbt"
	OperatorTypeEnumWebhook       OperatorTypeEnum = "webhook"
)

func (e OperatorTypeEnum) ToPointer() *OperatorTypeEnum {
	return &e
}

func (e *OperatorTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "normalization":
		fallthrough
	case "dbt":
		fallthrough
	case "webhook":
		*e = OperatorTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OperatorTypeEnum: %v", v)
	}
}
