// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ReleaseStageEnum string

const (
	ReleaseStageEnumAlpha              ReleaseStageEnum = "alpha"
	ReleaseStageEnumBeta               ReleaseStageEnum = "beta"
	ReleaseStageEnumGenerallyAvailable ReleaseStageEnum = "generally_available"
	ReleaseStageEnumCustom             ReleaseStageEnum = "custom"
)

func (e ReleaseStageEnum) ToPointer() *ReleaseStageEnum {
	return &e
}

func (e *ReleaseStageEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "alpha":
		fallthrough
	case "beta":
		fallthrough
	case "generally_available":
		fallthrough
	case "custom":
		*e = ReleaseStageEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReleaseStageEnum: %v", v)
	}
}
