// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SchemaChangeEnum string

const (
	SchemaChangeEnumNoChange    SchemaChangeEnum = "no_change"
	SchemaChangeEnumNonBreaking SchemaChangeEnum = "non_breaking"
	SchemaChangeEnumBreaking    SchemaChangeEnum = "breaking"
)

func (e SchemaChangeEnum) ToPointer() *SchemaChangeEnum {
	return &e
}

func (e *SchemaChangeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "no_change":
		fallthrough
	case "non_breaking":
		fallthrough
	case "breaking":
		*e = SchemaChangeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemaChangeEnum: %v", v)
	}
}
