// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SourceAuthSpecificationAuthTypeEnum string

const (
	SourceAuthSpecificationAuthTypeEnumOauth20 SourceAuthSpecificationAuthTypeEnum = "oauth2.0"
)

func (e SourceAuthSpecificationAuthTypeEnum) ToPointer() *SourceAuthSpecificationAuthTypeEnum {
	return &e
}

func (e *SourceAuthSpecificationAuthTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "oauth2.0":
		*e = SourceAuthSpecificationAuthTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceAuthSpecificationAuthTypeEnum: %v", v)
	}
}

type SourceAuthSpecification struct {
	AuthType *SourceAuthSpecificationAuthTypeEnum `json:"auth_type,omitempty"`
	// An object containing any metadata needed to describe this connector's Oauth flow
	Oauth2Specification *OAuth2Specification `json:"oauth2Specification,omitempty"`
}
