// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SourceDefinitionSpecificationRead - Successful operation
type SourceDefinitionSpecificationRead struct {
	AdvancedAuth      *AdvancedAuth            `json:"advancedAuth,omitempty"`
	AuthSpecification *SourceAuthSpecification `json:"authSpecification,omitempty"`
	// The specification for what values are required to configure the sourceDefinition.
	ConnectionSpecification map[string]interface{} `json:"connectionSpecification,omitempty"`
	DocumentationURL        *string                `json:"documentationUrl,omitempty"`
	JobInfo                 SynchronousJobRead     `json:"jobInfo"`
	SourceDefinitionID      string                 `json:"sourceDefinitionId"`
}
