// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type StreamTransformTransformTypeEnum string

const (
	StreamTransformTransformTypeEnumAddStream    StreamTransformTransformTypeEnum = "add_stream"
	StreamTransformTransformTypeEnumRemoveStream StreamTransformTransformTypeEnum = "remove_stream"
	StreamTransformTransformTypeEnumUpdateStream StreamTransformTransformTypeEnum = "update_stream"
)

func (e StreamTransformTransformTypeEnum) ToPointer() *StreamTransformTransformTypeEnum {
	return &e
}

func (e *StreamTransformTransformTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "add_stream":
		fallthrough
	case "remove_stream":
		fallthrough
	case "update_stream":
		*e = StreamTransformTransformTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StreamTransformTransformTypeEnum: %v", v)
	}
}

type StreamTransform struct {
	StreamDescriptor StreamDescriptor                 `json:"streamDescriptor"`
	TransformType    StreamTransformTransformTypeEnum `json:"transformType"`
	// list of field transformations. order does not matter.
	UpdateStream []FieldTransform `json:"updateStream,omitempty"`
}
