// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SyncModeEnum string

const (
	SyncModeEnumFullRefresh SyncModeEnum = "full_refresh"
	SyncModeEnumIncremental SyncModeEnum = "incremental"
)

func (e SyncModeEnum) ToPointer() *SyncModeEnum {
	return &e
}

func (e *SyncModeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "full_refresh":
		fallthrough
	case "incremental":
		*e = SyncModeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SyncModeEnum: %v", v)
	}
}
